### ISSUE TITLE
Can you describe why this is on-hold?

### ISSUE THREAD

**Issue by AJTJ** [phated/twentyfive-stars#11]
I'm considering building out a CRUD server using `actix-web` and `async_graphql` amongst other services and it would be interesting to hear your thoughts. 

Other than why your project is currently on hold (for Context?), can you also explain why you switched from diesel to sqlx? I've played with sqlx, but it is not anywhere near as robust as diesel is.

I've got my proposed tech stack here in my README.md: https://github.com/AJTJ/free_rust
it would be great to hear your thoughts on it, considering how much work you've put into this project.
Ultimately my application will be a pretty straightforward CRUD app.

Thanks!

**Comment by phated** [comment]
Sorry, I don't really have the time or energy to do that. ☹️
